server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 11177
  servlet:
    context-path: /patient-wx-api
#192.168.122.3
spring:
  datasource:
#    tdengine:
#      username: 'root'
#      password: 'taosdata'
#      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
#      minimum-idle: 10
#      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
#      maximum-pool-size: 20
#      #自动提交从池中返回的连接，默认值为true
#      auto-commit: true
#      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
#      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
#      idle-timeout: 30000
#      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短；单位ms
#      max-lifetime: 55000
#      #连接超时时间:毫秒，小于250毫秒，会被重置为默认值30秒
#      connection-timeout: 1000
#      jdbc-url: 'jdbc:TAOS-RS://127.0.0.1:6041/power?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8'
#      driver-class-name: 'com.taosdata.jdbc.rs.RestfulDriver'
#    phoenix:
#      driver-class-name: org.apache.phoenix.queryserver.client.Driver
#      jdbcUrl: jdbc:phoenix:thin:url=http://49.7.106.164:11166;serialization=PROTOBUF
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        test-on-borrow: true
#        test-while-idle: true
#        max-active: 8
#        min-idle: 4
#        validation-query: SELECT 1
#
    url: jdbc:mysql://localhost:3306/weilandb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT "1"
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    #如果是oracle 则可以设置为true  如果是mysql则设置false 分库分表较多的数据库，建议配置为false。
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
    # 过滤器设置（第一个stat很重要，没有的话会监控不到SQL）
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true



  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 0
    host: 49.7.106.164
    port: 11176
    password: deech3oo-redis
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8


  quartz:
    job-store-type: memory
tdengine:
  executor:
    thread:
      core_pool_size: 20
      max_pool_size: 20
      queue_capacity: 20000
      name:
        prefix: tdengine-write-
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.patient.wx.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.patient.wx.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  #token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  token-style: uuid
  isReadCookie: false


udp:
  server:
    port: 63333

tcp:
  server:
    port: 63333

